# Generated by Django 5.0.1 on 2024-01-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('publish_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1500)),
                ('code', models.CharField(default='qBsXiQWSvRSFPiv5BOcpJ20RtmXcO8Xzlmouo0JRZnJIplXeg1', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
