# Generated by Django 5.0.1 on 2024-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='D3jZR77ZCjODx0MTJB9nNyedqiqbPxDWFuis1sWLNgZYSLWesk', max_length=50),
        ),
    ]
