# Generated by Django 5.0.1 on 2024-01-19 16:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='m3FlTD8CrrcZPANy5BCWGDCd76HJaU4a9V9VbVC39ibwRzFDSA', max_length=50),
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('publish_at', models.DateTimeField(default=datetime.datetime(2024, 1, 19, 16, 35, 44, 10150, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writers', models.ManyToManyField(related_name='writers', to='book.book')),
            ],
        ),
    ]
