# Generated by Django 5.0.1 on 2024-01-21 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_code_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='68VXiVT8q7PwdQZJJzcS1kAXpKbzZEiFDUpEwUPQeOk3vAeVGC', max_length=50),
        ),
        migrations.AlterField(
            model_name='writer',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 14, 36, 16, 754456, tzinfo=datetime.timezone.utc)),
        ),
    ]
