# Generated by Django 5.0.1 on 2024-01-21 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_code_alter_writer_publish_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='writers',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='U8DD7bUwnoxz6HNkFK6AhRDfHjP67WLCzHFGVcjxE5XtIvVZIg', max_length=50),
        ),
        migrations.AlterField(
            model_name='writer',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 15, 40, 40, 264000, tzinfo=datetime.timezone.utc)),
        ),
    ]
