# Generated by Django 5.0.1 on 2024-01-21 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_writers_writer_book_alter_book_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='6aUikclnNWiN6zc8B4MU0iuUSbY72hVuMvA0pZbAUYYYGdyurE', max_length=50),
        ),
        migrations.AlterField(
            model_name='writer',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 15, 41, 52, 717765, tzinfo=datetime.timezone.utc)),
        ),
    ]
